//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peleg.Flt_FlightProcessingLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightProcessingLog
    {
        public int Id { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
        public string FlightIdentifier { get; set; }
        public string Step { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Message { get; set; }
        public string SourceXml { get; set; }
        public string MessageType { get; set; }
    }
}
